---
- name: register to RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
    pool: "{{ pool }}"
  tags: sub-mgr

- name: enable repos
  shell: "subscription-manager repos --list-enabled | grep 'Repo ID:   {{ item }}' || subscription-manager repos --enable={{ item }}"
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-openstack-6.0-rpms
    - rhel-server-rhscl-7-rpms
    - rhel-ha-for-rhel-7-server-rpms
    - rhel-7-server-optional-rpms
  register: result
  changed_when: result.stdout.find('enabled') != -1
  tags: sub-mgr
